### ISSUE TITLE
Logs not uploading to Cloudwatch Logs out of the box

### ISSUE THREAD

**Issue by bounav** [aws-samples/amazon-aurora-proxysql-example#3]
Hello,

It might sound obvious to someone used to working with cloud formation, but If you try to use this template "as provided" the template creates an EC2 instance for `proxysql` without specifying an EC2 role (or creating an EC2 role using cloudformation...) which will prevent the instance from pushing its logs to Cloudwatch Logs.

In `proxysql.yaml`, a log group is created with a retention of 7 days

```yaml
Resources:
  ProxySQLLogs:
      Type: AWS::Logs::LogGroup
      DeletionPolicy: Retain
      Properties:
        RetentionInDays: 7
```

And later on in the same yaml file the `install_logs` section installs and configure `awslogs` to publish logs files...

In my opinion this should either be mentioned in the `README.md` file or the template improved to generate the required role using cloud formation.

I ended adding the following line `IamInstanceProfile: "ec2-proxysql-prod"` to the `sqlproxy.yaml` template to tell the autoscaling module of cloudformation to assign a role to the instances it creates:

```yaml
LaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", AMALINUX]
      InstanceType: !Ref InstanceSize
      AssociatePublicIpAddress: true # The instance should have a public IP to be able to download their software (or they would have to be on a subnet with a NAT gateway)
      IamInstanceProfile: "ec2-proxysql-prod"
```

Then I assigned the policy `CloudWatchLogsFullAccess` to my `ec2-sqlproxy-prod` role, then rebuilt my stack and now I can see the logs in cloudwatch.
